### ISSUE TITLE
Remove `default_workitem_type` option 

### ISSUE THREAD

**Issue by timvink** [ing-bank/doing-cli#66]
Currently, we have an optional `default_workitem_type` setting in the config that controls the work item type when using `doing create issue` and `doing workon`.

Instead, we should encourage & document the use of `defaults`:

```yaml
# .doing-cli-config.yml

defaults:
    DOING_CREATE_ISSUE_TYPE: 'Bug'
    DOING_WORKON_TYPE: 'Bug'
```
