### ISSUE TITLE
Not all work items type are listed

### ISSUE THREAD

**Issue by MHeus** [ing-bank/doing-cli#78]
Eg Test Case work items have a different workflow states (Design -> Ready -> Closed) than currently selected by doing.

Fix: improve state selection in the `work_item_query` in `__list.py` :

```
   if state == "open":
        query += "AND [System.State] IN ('Active', 'New', 'To Do', 'Doing', 'Approved', 'Committed', 'Proposed') "
    if state == "closed":
        query += "AND [System.State] IN ('Resolved','Closed','Done') "
    if state == "all":
        query += "AND [System.State] <> 'Removed' "
```

**Comment by timvink** [comment]
Because different companies can create custom work item states, I'd like to have this configurable via `.doing-cli-config.yml`.

For example:

```yaml
# .doing-cli-config.yml
work_item_open_states: ["Active", ...]
work_item_closed_states: ["Resolved", ...]
```

If not specified, we use the current defaults.

That said, `Ready` can be added to the current defaults, makes sense.
